MACOSX_SDK_VERSION:            # [osx and x86_64]
  - 11.0                       # [osx and x86_64]
c_compiler_version:    # [osx]
  - 20.1             # [osx]
lld:                   # [osx]
  - 20.1             # [osx]
